import { Doctor, DoctorSpecialty } from "@/types/doctor.types";

// Static doctors data
export const staticDoctors: Doctor[] = [
  {
    id: "static-1",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-2",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-3",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-4",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-5",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-6",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-7",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-8",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-9",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-10",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-11",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-12",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-13",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-14",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-15",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-16",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-17",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-18",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-19",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-20",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-21",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-22",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-23",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-24",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-25",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-26",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-27",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-28",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-29",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-30",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-31",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-32",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-33",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-34",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-35",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-36",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-37",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-38",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-39",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-40",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-41",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-42",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-43",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-44",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-45",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },

  {
    id: "static-46",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-47",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-48",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-49",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-50",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-51",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-52",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-53",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-54",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-55",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-56",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-57",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-58",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-59",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-60",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },

  {
    id: "static-61",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-62",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-63",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-64",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-65",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-66",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-67",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-68",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-69",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-70",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-71",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-72",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-73",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-74",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-75",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-76",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-77",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-78",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-79",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-80",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-81",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-82",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-83",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-84",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-85",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-86",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-87",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-88",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-89",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-90",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-91",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-92",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-93",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-94",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-95",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-96",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-97",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-98",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-99",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
  {
    id: "static-100",
    name: "Dr. Vüsal Babayev",
    email: "vusal.babayev@example.com",
    phone: "+994 51 567 89 01",
    specialty: DoctorSpecialty.Uroloq,
    rating: 4.9,
    reviews: 112,
    image: "/doctor-image.jpg",
    workAddress: "Azadlıq prospekti 77, Bakı",
    location: {
      latitude: 40.3901,
      longitude: 49.8599,
    },
  },
  {
    id: "static-101",
    name: "Dr. Əli Məmmədov",
    email: "ali.mammadov@example.com",
    phone: "+994 50 123 45 67",
    specialty: DoctorSpecialty.Kardioloq,
    rating: 4.8,
    reviews: 124,
    image: "/doctor-image.jpg",
    workAddress: "Nizami küçəsi 15, Bakı",
    location: {
      latitude: 40.3753,
      longitude: 49.8371,
    },
  },
  {
    id: "static-102",
    name: "Dr. Sevda Quliyeva",
    email: "sevda.quliyeva@example.com",
    phone: "+994 55 234 56 78",
    specialty: DoctorSpecialty.Nevroloq,
    rating: 4.9,
    reviews: 87,
    image: "/doctor-image.jpg",
    workAddress: "28 May küçəsi 42, Bakı",
    location: {
      latitude: 40.3777,
      longitude: 49.8456,
    },
  },
  {
    id: "static-103",
    name: "Dr. Farid Hüseynov",
    email: "farid.huseynov@example.com",
    phone: "+994 70 345 67 89",
    specialty: DoctorSpecialty.Pediatr,
    rating: 4.7,
    reviews: 156,
    image: "/doctor-image.jpg",
    workAddress: "Xətai prospekti 33, Bakı",
    location: {
      latitude: 40.3892,
      longitude: 49.8522,
    },
  },
  {
    id: "static-104",
    name: "Dr. Leyla Nəsirova",
    email: "leyla.nasirova@example.com",
    phone: "+994 77 456 78 90",
    specialty: DoctorSpecialty.Dermatoloq,
    rating: 4.6,
    reviews: 93,
    image: "/doctor-image.jpg",
    workAddress: "İnşaatçılar prospekti 55, Bakı",
    location: {
      latitude: 40.381,
      longitude: 49.8498,
    },
  },
];
